# Impact Analysis Configuration
# This file contains parameters for generating heatmaps and risk analysis

impact_analysis:
  # Grid resolution settings
  grid:
    resolution_degrees: 0.1
    landslide_computation_resolution_degrees: 0.01
    landslide_visualization_resolution_degrees: 0.1
  
  # Landslide ensemble configuration
  landslide:
    ensemble:
      num_members: 50
      spatial_correlation_radius: 2
      correlation_method: "gaussian_local"
      random_seed: 42
  
  # Output settings
  output:
    base_directory: "data/results/impact_analysis"
    cache_directory: "data/results/impact_analysis/cache"
  
  # Input data paths
  input:
    school_data: "data/raw/sinapred/nic_schools.geojson"
    population_data: "data/raw/census"
    poverty_data: "data/raw/gadm/nicaragua_departments.geojson"
    shelter_data: "data/raw/sinapred/shelters_nic.geojson"
    health_facility_data: "data/raw/sinapred/health_facilities_nic.geojson"
    flood_data: "data/preprocessed/flood/nicaragua_flood_extent_20201117.tif"
    landslide_data: "data/preprocessed/landslide"
    hurricane_data: "data/preprocessed/weatherlab/synthetic/processed_FNV3_2024_11_04_00_00_ensemble_data_synthetic.csv"
  
  # Analysis runs
  runs:
    # hurricane:
    #   - schools
    #   - school_population
    #   - health_facilities
    #   - health_facilities_population
    #   - shelters
    #   - shelters_population
    #   - population
    #   - children
    #   - poverty
    #   - poverty_children
    #   - severe_poverty
    #   - severe_poverty_children
    # landslide:
    #   - schools
    #   - school_population
    #   - health_facilities
    #   - health_facilities_population
    #   - shelters
    #   - shelters_population
    #   - population
    #   - children
    #   - poverty
    #   - poverty_children
    #   - severe_poverty
    #   - severe_poverty_children
    - flood
      - schools
