# Configuration for synthetic hurricane generation
# This file contains parameters to shift hurricane tracks by specified deltas

synthetic_hurricane:
  # Latitude and longitude offsets to apply to hurricane tracks
  # Positive delta_latitude moves track north, negative moves south
  # Positive delta_longitude moves track east, negative moves west
  delta_latitude: -7.5262    # degrees - move track 2 degrees north
  delta_longitude: -1.3784  # degrees - move track 1.5 degrees west
  
  # Input and output settings
  input:
    source_file: "processed_FNV3_2024_11_04_00_00_ensemble_data.csv"  # Source hurricane file
    data_dir: "data/preprocessed/weatherlab/processed"  # Directory containing processed hurricane data
  
  output:
    data_dir: "data/preprocessed/weatherlab/synthetic"  # Directory for synthetic hurricane data
    file_suffix: "_synthetic"  # Suffix to add to output filename
    
  # Processing options
  processing:
    preserve_original_track_id: false  # Whether to keep original track_id or generate new one
    new_track_id: "SYNTHETIC_001"  # New track ID for synthetic hurricane
    update_metadata: true  # Whether to update metadata fields 

  # Grid heatmap settings
  grid_heatmap:
    resolution_degrees: 0.1  # Grid cell size in degrees for Nicaragua heatmap
 