# Example configuration file

data:
  input_path: "../data/input.csv"
  output_path: "../data/output.csv"
  batch_size: 64

analysis:
  method: "regression"
  threshold: 0.05

optimization:
  algorithm: "genetic"
  max_iterations: 1000
  tolerance: 1e-4 